functionsDirectory = "/Users/cc3po/.openclaw/workspace/cc3po-io-astro/netlify/functions"
functionsDirectoryOrigin = "default"
headersOrigin = "config"
plugins = []

[build]
publish = "/Users/cc3po/.openclaw/workspace/cc3po-io-astro/dist"
publishOrigin = "config"
commandOrigin = "config"
command = "npm run build"
functions = "/Users/cc3po/.openclaw/workspace/cc3po-io-astro/netlify/functions"

[build.environment]
NODE_VERSION = "22"
ZOOM_ACCOUNT_ID = "mhC4aS5_TK6F_QqwRBdRJA"
ZOOM_CLIENT_ID = "Pzo7Hiq7QI61WEUGvySDKg"
ZOOM_CLIENT_SECRET = "ioftUX58gTpj65yRaYRPmVnZQOmJEKlc"
SUPABASE_URL = "https://cdrcgmdvepxwsbqaifxv.supabase.co"
SUPABASE_ANON_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImNkcmNnbWR2ZXB4d3NicWFpZnh2Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NzM1MDY4MDksImV4cCI6MjA4OTA4MjgwOX0.pKWLWvsSimTOMkpaXKKrLJESrQEMUayUU1c9ANzr1Dc"

[build.processing]

[build.processing.css]

[build.processing.html]

[build.processing.images]

[build.processing.js]

[build.services]

[functions]

[functions."*"]

[[headers]]
for = "/*"

[headers.values]
X-Frame-Options = "DENY"
X-XSS-Protection = "1; mode=block"
X-Content-Type-Options = "nosniff"
Referrer-Policy = "strict-origin-when-cross-origin"

[[headers]]
for = "/assets/*"

[headers.values]
Cache-Control = "public, max-age=31536000, immutable"

[[redirects]]
from = "/*"
to = "/index.html"
status = 200.0
force = false

[redirects.query]

[redirects.conditions]

[redirects.headers]